# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: Test Agent

variables:
  buildConfiguration: 'Release'
  buildPath: './DashboardApi'
  dotnet: /home/boba/.dotnet/dotnet

steps:
- script: $(dotnet) restore $(buildPath)
  displayName: 'dotnet restore $(buildPath)'

- script: $(dotnet) build $(buildPath) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildPath) --configuration $(buildConfiguration)'
  
- script: $(dotnet) publish $(buildPath) --configuration $(buildConfiguration) -r linux-arm -o ~/Test
  displayName: 'dotnet publish $(buildPath) --configuration $(buildConfiguration) -r linux-arm -o ~/Test'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'dashboard-api'


