# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  name: Test Agent

variables:
  buildConfiguration: 'Release'
  buildPath: './DashboardApi'
  dotnet: /home/boba/.dotnet/dotnet
  outputPath: /home/boba/www/DashboardApi

steps:
- script: $(dotnet) restore $(buildPath)
  displayName: 'dotnet restore $(buildPath)'

- script: $(dotnet) build $(buildPath) --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildPath) --configuration $(buildConfiguration)'
  
- script: $(dotnet) publish $(buildPath) --configuration $(buildConfiguration) -r linux-arm -o $(outputPath)
  displayName: 'dotnet publish $(buildPath) --configuration $(buildConfiguration) -r linux-arm -o $(outputPath)'

- script: sudo systemctl stop dashboardapi-kestrel.service
  displayName: 'Stopping DashboardingApi kestrel'

- script: sudo systemctl start dashboardapi-kestrel.service
  displayName: 'Starting DashboardingApi kestrel'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'dashboard-api'


